### PR TITLE
1.x

### PR DESCRIPTION
**Pull request by stas**
Some fixes to make lookit usable.
Issues listed in commits.

### CODE REVIEW

**Comment by zachtib** [comment]
Merged for now, but I'll want to put an option on the Selector before 1.2, since it does work for a lot of people (including me). The main issue seems to have been Intel graphics on 11.04. Probably a drop down in the Preferences for Selector = (Fancy, Simple, None)

**Comment by stas** [comment]
Thanks for the merge.
I'm on Oneiric, with an Intel card, and all those fixes made lookit back usable for me.

As for me, I would go with simply 2 options: Default, and Fallback (as it's now). Where the second will not be fancy but should work for everybody.

Anyway, great work on this project, it's a must be installed for my desktop.

**Comment by stas** [comment]
Hey, could you update the PPA with this branch please?
Thanks in advance.

**Comment by zachtib** [comment]
Yeah, I'll try to get around to putting a release together when I get home
from work

On Fri, Sep 23, 2011 at 2:22 PM, Stas Sușcov <
reply@reply.github.com>wrote:

> Hey, could you update the PPA with this branch please?
> Thanks in advance.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zachtib/lookit/pull/37#issuecomment-2181352

## 

Zach Tibbitts

**Comment by stas** [comment]
On Vi 23 sep 2011 22:25:34 +0300, Zach Tibbitts wrote:

> Yeah, I'll try to get around to putting a release together when I get home
> from work

Thanks a lot. Much appreciated

**Comment by zachtib** [comment]
At the very least, I'll get something into the testing ppa. I'm running Arch
as my primary distro now, so I'd like to fix the lingering Arch-related bugs
before I push out 1.2.

On Fri, Sep 23, 2011 at 3:32 PM, Stas Sușcov <
reply@reply.github.com>wrote:

> On Vi 23 sep 2011 22:25:34 +0300, Zach Tibbitts wrote:
> 
> > Yeah, I'll try to get around to putting a release together when I get
> > home
> > from work
> 
> Thanks a lot. Much appreciated
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zachtib/lookit/pull/37#issuecomment-2181992

## 

Zach Tibbitts

**Comment by stas** [comment]
Hello,
any updates for the ppa?
Thanks.

**Comment by zachtib** [comment]
This completely slipped my mind. I'm currently setting up an Ubuntu VM so
that I can build packages.

On Sun, Oct 16, 2011 at 1:55 PM, Stas Sușcov <
reply@reply.github.com>wrote:

> Hello,
> any updates for the ppa?
> Thanks.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zachtib/lookit/pull/37#issuecomment-2422028

## 

Zach Tibbitts

**Comment by stas** [comment]
I think you can use dput and just sign the changelog file and launchpad will do the rest.
Was playing some time ago with it and it saved me from installing the whole dpkg toolchain.

**Pull request merged**
