### PR TITLE
implement configurable CloudApp API url

### PR DESCRIPTION
**Pull request by posativ**
With [regenwolken](https://github.com/posativ/regenwolken/) – yes, a shameless self-promote – exists an alternate implementation of the CloudApp API that is completely open source and simple to install.

In addition the user can use HTTPS for secure transport. Actually this is not a feature request of mine (I do not use a Linux Desktop), but of a friend that needs a nice integrated tool like lookit is :)

I hope I made everything right with the GUI part. Unfortunately Unity did not launch the GUI of lookit and I had to use `lookit --preferences`.

### CODE REVIEW

**Comment by cmur2** [comment]
+1 I would really appreaciate to see this feature in lookit!

**Comment by Dirrot** [comment]
+1 is a merge still possible? i would like to use it soon.

**Comment by zachtib** [comment]
If someone will confirm that this patch still works, I'll merge it in

**Comment by jgraichen** [comment]
I can confirm the patch still works at least with the code from `1.1.0-0~ppa1`.

```
> curl https://github.com/zachtib/lookit/pull/51.patch | patch
patching file cloud.py
patching file cloud.py
patching file cloud.py
patching file cloud.py
patching file preferences.py
Hunk #1 succeeded at 81 with fuzz 2 (offset -4 lines).
patching file uploader.py
Hunk #1 succeeded at 132 (offset -51 lines).
Hunk #2 succeeded at 201 with fuzz 2 (offset -55 lines).
patching file cloud.py
patching file uploader.py
Hunk #1 succeeded at 46 (offset -2 lines).
```

**Pull request closed without merging**
